# Setup
name:         SciFT
tagline:      Scientific Fortran Tools
baseurl:      "/scift"

# Gems
gems:
  - jekyll-paginate
  
#Others
markdown: kramdown

# gem install kramdown rouge
#highlighter: pygments
#kramdown:
  #input: GFM
  #syntax_highlighter: rouge
  
highlighter: rouge

include: ['_pages']